[global]
# Development settings
developmentMode = false

[server]
# Server configuration for Streamlit Community Cloud
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

# File upload settings
maxUploadSize = 200

# WebSocket settings
maxMessageSize = 200

[browser]
# Browser settings
gatherUsageStats = false

[theme]
# Custom theme for Mowbot Fleet Dashboard
primaryColor = "#00ff88"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[client]
# Client-side settings
showErrorDetails = true
toolbarMode = "minimal"

[runner]
# Fast reruns for better development experience
fastReruns = true
enforceSerializableSessionState = false
